name: Run Program

on:
  push:
    branches:
      - main
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run_program:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: 3.12.6
          # Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv, poetry.
          cache: pipenv

      - name: Install Dependencies
        run: |
          pip3 install --upgrade pipenv
          pipenv install

      - name: Run Python Program
        run: |
          pipenv run ./main.py

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
